### ISSUE TITLE
Cache configuration via environment variables

### ISSUE THREAD

**Issue by jlelse** [willnorris/imageproxy#151]
Especially for use with Docker support for cache configuration via env vars would be awesome. I don't know if I'm missing anything, but I wasn't able to find that option.

**Comment by NARKOZ** [comment]
>nothing in the imageproxy package should be reading configuration from flags or environment variables.

https://github.com/willnorris/imageproxy/pull/83#issuecomment-285721790

**Comment by willnorris** [comment]
My comment on #83 was specifically about the imageproxy package (as opposed to the main package).  Any option parsing should happen in the main package, and then values passed into the imageproxy package.

I standardized on flags for all of the options, just because that's what I'm used to, and is the most straightforward to document with the flag package.  Is there a specific reason why environment variables are simpler for docker?  I'm honestly asking, since I don't really use docker myself.

**Comment by Strayer** [comment]
To add a simple case where this would be useful: When using docker-compose, one can create a .env file in the same directory as docker-compose.yml and then just reference the environment variables:

```yaml
version: "3.1"

services:
  app:
    image: ...
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_STORAGE_BUCKET_NAME:
```

This is great since you can simply commit your docker-compose.yml and an example.env without exposing secrets in git or having to modify committed code on deployments.

Also, when using Kubernetes, its kind of standard to just pull in secrets as environments into pods:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never
```

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

Additionally, containers on Heroku are also usually configured by environment variables.

Right now, you'd have to utilize the variable substitution feature of docker-compose:

```yaml
version: "3.1"

services:
  app:
    image: willnorris/imageproxy
    command: -signatureKey ${SIGNATURE_KEY}
```

Works, but it just feels… unusual to me. Not sure how it could be done on Heroku and Kubernetes, but probably in a comparable way.

Also, not that it matters _that_ much, having the secrets in the command may expose them to applications being able to list running processes. Only root and the process owner can inspect the processes environment variables in /proc on linux systems, so its a tad bit more secure this way.

Sorry for the wall of text :)
