### ISSUE TITLE
Bug: In the latest image I am unable to cache the images in the local disk

### ISSUE THREAD

**Issue by brahmeshwar** [willnorris/imageproxy#198]
I am using the 
docker run -v /tmp/ttt:/tmp/imageproxy  -p 8080:8080 willnorris/imageproxy -addr 0.0.0.0:8080 -cache /tmp/imageproxy this command and executing the images on port :8080 but I am unable to find any cached results in the directory path /tmp/ttt. Can I know how to fix it? I am able to cache the results with docker image with tag v0.8.0.

**Comment by willnorris** [comment]
chmoding inside the image doesn't make a difference (which makes sense).  The most straightforward way seems to be to create the cache directory ahead of time, and make sure the container is running as a user which has write access to that directory.  

So for example, to create the directory and run the container as your current user:

```sh
# make cache direct, and ensure it is owned by current user in case it already existed
mkdir /tmp/ttt && chown $(whoami) /tmp/ttt
docker run -u $(id -u) -v /tmp/ttt:/tmp/imageproxy -p 8080:8080 willnorris/imageproxy:v0.9.0 -addr 0.0.0.0:8080 -cache /tmp/imageproxy -verbose
```

So this all seems to be working as intended (from a docker permission perspective), it's just a little surprising since we changed how the container runs.  I'll see about updating the docs to make this clearer.

**Comment by nhh** [comment]
Hi,

I've configured imageproxy with docker-compose but I am not able to see any images being served from cache.

My Config:

```yml
  imageproxy:
    image: ghcr.io/willnorris/imageproxy
    restart: "unless-stopped"
    container_name: "imageproxy"
    user: "1000"
    volumes:
      - "./data/imageproxy/cache:/tmp/imageproxy"
    env_file:
      - "./config"
 ```
 
 My config file:
 
```
# Image Proxy

IMAGEPROXY_ADDR=0.0.0.0:8080
IMAGEPROXY_CACHE=/tmp/imageproxy
```

I've created the cache folder as user 1000, but its still not writeable. How can I verify that the configuration is correct? With -verbose enabled I dont see any file writing issues/exceptions.
