### ISSUE TITLE
How to configure for docker cloud: service can't be reached

### ISSUE THREAD

**Issue by metalaureate** [willnorris/imageproxy#57]
Sorry if this is a stupid question... I deployed the docker image to docker cloud. It works inside the remote terminal (localhost:8080), but the service is unreachable outside the container.

My docker-compose file looks like:

```
imageproxy:
  image: 'willnorris/imageproxy:latest'
  ports:
    - '8080:8080'
```

I'm assuming the internal web service is blocking connections but I am not savvy enough to know how to configure it.

Thank you for an otherwise awesome service and I look forward to be being able to deploy it to docker cloud once I have figured this out.

**Comment by willnorris** [comment]
No clue, I don't actually use docker myself

/cc @sevki who might be able to help.

**Comment by metalaureate** [comment]
Thank you for your prompt response.

@sevki I have the same problem using sevki/imageproxy

Your docker run example command uses 'addr'

`docker run -p 8080:8080 willnorris/imageproxy -addr 0.0.0.0:8080`

I do not know what the analog is for that in docker-compose. `-addr` is not mentioned in any of the `docker run` documentation I looked at here: https://docs.docker.com/engine/reference/run/

My previous experience with docker images that host web service is that you expose ports and you're done.

**Comment by sevki** [comment]
hey @metalaureate 
can you give me more information about what you are trying to run this on (osx, linux) and what it is exactly you are trying to do

**Comment by metalaureate** [comment]
It's definitely working inside its container, just to rule that out:

![image](https://cloud.githubusercontent.com/assets/2185884/14156377/fa885d44-f67a-11e5-84de-8b46e8e538fb.png)

**Comment by metalaureate** [comment]
@sevki  hi! I am trying to create an http imageproxy service for my application by deploying the image to an EC2 instance, using Docker Cloud.

**Comment by sevki** [comment]
analog for that in compose would be something along the lines of 
```
imageproxy:
  image: 'willnorris/imageproxy:latest'
  command: /go/bin/imageproxy -addr 0.0.0.0:8080
  ports:
    - '8080:8080'
```
